env: DISPLAY=:99.0

language: java

before_install:
  - git clone https://github.com/processing/processing
  - cd processing/build
  - ant
  - cd ../..
  - "sh -e /etc/init.d/xvfb start"

script: ant -Dprocessing=processing test

