env: DISPLAY=:99.0

sudo: false

language: java

jdk: oraclejdk8

before_install:
  - git clone --depth=1 https://github.com/processing/processing
  - cd processing/build
  - ant
  - cd ../..
  - git clone --depth=1 https://github.com/processing/processing-video
  - cd processing-video
  - ant -Dcore.classpath.location="../processing/core/library/"
  - cd ..
  - "sh -e /etc/init.d/xvfb start"

script: ant -Dprocessing=processing -Dprocessing-video=processing-video test

